//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDBSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.DriversCars = new HashSet<DriversCars>();
            this.Incident = new HashSet<Incident>();
        }
    
        public string mark { get; set; }
        public int markid { get; set; }
        public string model { get; set; }
        public long madeYear { get; set; }
        public string color { get; set; }
        public string StateNumber { get; set; }
        public System.DateTime dateOfRegistration { get; set; }

        public string MarkTest { get
            {
                if (MarkAll == null)
                    return "";
                else
                    return
                        MarkAll.MarkTitle;

            }
        }
       public virtual MarkAll MarkAll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriversCars> DriversCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incident { get; set; }

    }
}
