//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDBSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriversCars
    {
        public long idDriver { get; set; }
        public string idCar { get; set; }
        public System.DateTime dateStartHaving { get; set; }
        public Nullable<System.DateTime> dateEndhaving { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
