//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDBSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentsVolations
    {
        public long idIncident { get; set; }
        public long idVolation { get; set; }
        public decimal penalty { get; set; }
        public long statePenalty { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual State State { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
