//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDBSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkAll
    {
        public MarkAll()
        {
            this.Car = new HashSet<Car>();
        }
        public long MarkID { get; set; }
        public string MarkTitle { get; set; }

        public virtual ICollection<Car> Car { get; set; }
    }
}
